<a href="https://colab.research.google.com/github/AndresPautrat/IA_UPC/blob/main/SeleccionNatural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
import random

def Parejas(N):
    Aleatorio = random.sample(range(int(N/2),N),int(N/2))
    Pareja = {}
    for i in range(int(N/2)):
        Pareja[i] = Aleatorio[i]
        Pareja[Aleatorio[i]] = i
    return Pareja

def Inicializacion(N):
    global Individuos
    global Mejor
    Individuos = {}
    for i in range(N):
        Individuos[i] = numpy.random.choice(range(1,N+1),N,replace=True)
    print('---Inicializacion----')
    Mostrar(N)
	
def Seleccion(N):
    print('---Seleccion----')
    Pareja = Parejas(N)
    print('Parejas',Pareja)
    for k,v in Pareja.items():
        if Idoneidad(Individuos[k]) >= Idoneidad(Individuos[v]):
            Individuos[v] = Individuos[k]
    Mostrar(N)
            
def Idoneidad(Tablero):
    Atacadas = 0
    for i in range(len(Tablero)):
        for j in range(i + 1,len(Tablero)):
            if Tablero[i] == Tablero[j]:
                Atacadas += 1
            Dif = j - i
            if Tablero[i] == Tablero[j] - Dif or Tablero[i] == Tablero[j] + Dif:
                Atacadas += 1
    return (N*(N-1)/2-Atacadas)

def Cruce(N):
    print('-----Cruce ------')
    Pareja = Parejas(N)
    print('Parejas',Pareja)
    item = 0
    for k,v in Pareja.items():
        if item % 2 == 0:
            Punto = random.randint(1,N-2)
            print('punto',Punto)
            Hijo1 = []
            Hijo2 = []
            Padre1 = Individuos[k]
            Padre2 = Individuos[v]
            Hijo1.extend(Padre1[0:Punto])
            Hijo1.extend(Padre2[Punto:])
            Hijo2.extend(Padre2[0:Punto])
            Hijo2.extend(Padre1[Punto:])
            Individuos[k] = Hijo1
            Individuos[v] = Hijo2
        item = item+1
    Mostrar(N)

def Mostrar(N):
    for i in range(N):
        print(Individuos[i],'f(x)=',Idoneidad(Individuos[i]))

N = 8
Inicializacion(N)
Seleccion(N)
Cruce(N)


---Inicializacion----
[2 4 1 6 1 3 6 3] f(x)= 23.0
[5 5 8 7 6 1 1 2] f(x)= 20.0
[5 1 5 4 3 8 3 8] f(x)= 20.0
[3 5 1 7 5 8 3 3] f(x)= 19.0
[3 1 5 6 1 4 6 5] f(x)= 19.0
[7 6 1 1 8 8 1 8] f(x)= 19.0
[3 3 7 5 2 1 4 5] f(x)= 21.0
[5 5 1 3 4 8 5 4] f(x)= 20.0
---Seleccion----
Parejas {0: 6, 6: 0, 1: 4, 4: 1, 2: 5, 5: 2, 3: 7, 7: 3}
[2 4 1 6 1 3 6 3] f(x)= 23.0
[5 5 8 7 6 1 1 2] f(x)= 20.0
[5 1 5 4 3 8 3 8] f(x)= 20.0
[5 5 1 3 4 8 5 4] f(x)= 20.0
[5 5 8 7 6 1 1 2] f(x)= 20.0
[5 1 5 4 3 8 3 8] f(x)= 20.0
[2 4 1 6 1 3 6 3] f(x)= 23.0
[5 5 1 3 4 8 5 4] f(x)= 20.0
-----Cruce ------
Parejas {0: 6, 6: 0, 1: 5, 5: 1, 2: 4, 4: 2, 3: 7, 7: 3}
punto 4
punto 1
punto 1
punto 1
[2, 4, 1, 6, 1, 3, 6, 3] f(x)= 23.0
[5, 1, 5, 4, 3, 8, 3, 8] f(x)= 20.0
[5, 5, 8, 7, 6, 1, 1, 2] f(x)= 20.0
[5, 5, 1, 3, 4, 8, 5, 4] f(x)= 20.0
[5, 1, 5, 4, 3, 8, 3, 8] f(x)= 20.0
[5, 5, 8, 7, 6, 1, 1, 2] f(x)= 20.0
[2, 4, 1, 6, 1, 3, 6, 3] f(x)= 23.0
[5, 5, 1, 3, 4, 8, 5, 4] f(x)= 20.0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
x=numpy.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])
x


array(['piglet', 'pooh', 'Christopher', 'pooh', 'piglet'], dtype='<U11')